on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Audit
        run: |
          npm audit
      - name: Install & build
        run: |
          NODE_ENV=development npm install
          npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest
          access: public
          dry-run: false
          check-version: true
